spring.application.name=api

spring.datasource.url=jdbc:mysql://localhost:3306/bdd-nuevaera-dev
spring.datasource.username=root
spring.datasource.password=admin123

# Nos ayuda a indicar que cada que se inicie la app, la BD se va actualizar en caso de existir un cambio
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = none

#Nos ayuda a indicar la direccion de un archivo de carga de datos inicial
#Es recomendable solo cargarlo una sola vez
#spring.sql.init.chema=classpath:sql/custom-data.sql
#spring.sql.init.mode =always

spring.jpa.show-sql= true